import { Component, EventEmitter, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { BandService } from '../../../core/services/band.service';
import { Band } from '../../../core/models/band.model';

@Component({
  selector: 'app-add-band',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './add-band.component.html',
  styleUrls: ['./add-band.component.scss']
})
export class AddBandComponent {
  @Output() close = new EventEmitter<void>();
  @Output() bandAdded = new EventEmitter<void>();

  bandName: string = '';
  loading: boolean = false;
  error: string = '';
  successMessage: string = '';

  constructor(private bandService: BandService) {}

  onClose(): void {
    this.close.emit();
  }

  onSubmit(): void {
    if (!this.bandName.trim()) {
      this.error = 'Band name is required';
      return;
    }

    this.loading = true;
    this.error = '';
    this.successMessage = '';

    const newBand: Band = {
      id: '', // Will be generated by backend
      name: this.bandName.trim()
    };

    this.bandService.createBand(newBand).subscribe({
      next: () => {
        this.successMessage = 'Band added successfully!';
        this.loading = false;
        this.bandName = '';
        
        // Emit success and close modal after a short delay
        setTimeout(() => {
          this.bandAdded.emit();
          this.onClose();
        }, 1000);
      },
      error: (err) => {
        this.loading = false;
        this.error = err.error || 'Failed to add band. Please try again.';
        console.error('Error adding band:', err);
      }
    });
  }
}
